"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import socket
import time
import platform

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-u1c-n2k%7y7t)o5^b0t10osoya4m0w#lo(cqe@8f1p0b6t!_1+'
SECRET_KEY = os.getenv("SECRET")

CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",")

CORS_ALLOW_CREDENTIALS = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True')
if DEBUG.lower() in ('false', '0') or not DEBUG:
    DEBUG = False
else:
    DEBUG = True

DB_ADDRESS = ''

while not DB_ADDRESS:
    try:
        DB_ADDRESS = socket.gethostbyname(os.environ.get('DB_HOST', '172.17.0.2'))
    except Exception as e:
        print('DB Unavailable')
        print(os.environ.get('DB_HOST', '172.17.0.2'))
        time.sleep(10)

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'django_cleanup',
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "rest_framework",
    "drf_yasg",
    'corsheaders',
    'shortener.apps.ShortenerConfig',
    'account.apps.AccountConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
                BASE_DIR / 'templates',
                BASE_DIR / 'shortener' / 'templates',
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
     #   'ENGINE': 'django.db.backends.postgresql',
        'ENGINE': os.environ.get('DB_DRIVER'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': DB_ADDRESS,
        'PORT': os.environ.get('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# media files

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
PREFFIX_PATH=os.getenv("PREFIX_PATH", "")

if PREFFIX_PATH != "" and PREFFIX_PATH[-1] != "/":
    PREFFIX_PATH += "/"
MEDIA_URL = f'{PREFFIX_PATH}media/'

STATIC_URL = f'{PREFFIX_PATH}static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_FILES_DIRS = [
    BASE_DIR / "shortener" / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "account.CustomUser"

# deploy
USE_X_FORWARDED_HOST = os.getenv("USE_X_FORWARDED_HOST", 'False')
if USE_X_FORWARDED_HOST.lower() in ('false', '0') or not USE_X_FORWARDED_HOST:
    USE_X_FORWARDED_HOST = False
else:
    USE_X_FORWARDED_HOST = True
FORCE_SCRIPT_NAME = f'{os.getenv("PREFIX_PATH", "")}'
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(os.getenv("DATA_UPLOAD_MAX_NUMBER_FIELDS"))


if PREFFIX_PATH:
    LOGIN_REDIRECT_URL = f"{PREFFIX_PATH}"
else:
    LOGIN_REDIRECT_URL = "/"

# redis
if os.environ.get('REDIS_PROTOCOL', None) and os.environ.get('REDIS_HOST', None) and os.environ.get('REDIS_PORT', None):
    REDIS_URL = f"{os.environ.get('REDIS_PROTOCOL')}://{os.environ.get('REDIS_HOST')}:{os.environ.get('REDIS_PORT')}"
else:
    REDIS_URL = None


TESTING = 'test' in sys.argv
TESTING = TESTING or 'test_coverage' in sys.argv or 'pytest' in sys.modules
# Celery
CELERY_BROKER_URL = f'{REDIS_URL}/0'  # Redis как брокер
CELERY_RESULT_BACKEND = 'django-db'  # Сохранять результаты в БД Django
CELERY_RESULT_EXTENDED = True
CELERY_TASK_TRACK_STARTED = True
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Moscow'
CELERY_FLOWER_URL = os.getenv('celery_flower_url', '')

if platform.system() == 'Windows':
    # Для Windows используем solo
    CELERY_WORKER_POOL = 'solo'

if TESTING:
    CELERY_TASK_ALWAYS_EAGER = True

# Настройки коротких ссылок

SHORT_LINK_LENGTH = int(os.getenv("link_length", "8"))
SHORT_LINK_USE_DIGITS = bool(os.getenv("link_use_digits", 0))

# DRF
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
    "rest_framework_simplejwt.authentication.JWTAuthentication",
    "rest_framework.authentication.BasicAuthentication",
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv("THROTTLE_RATE_ANON", '500/day'),
        'user': os.getenv("THROTTLE_RATE_USER", '20000/day'),
    #    'send_lpr_basket_ready': os.getenv("THROTTLE_RATE_SEND_LPR_BASKET_READY", '1/hour'),
    },
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',),
    'DATE_FORMAT': "%d.%m.%Y",
    'DATETIME_FORMAT': "%d.%m.%y %H:%M:%S",
    # 'DEFAULT_PERMISSION_CLASSES': (
    #     'rest_framework.permissions.IsAuthenticated',
    # )
}

SWAGGER_SETTINGS = {
   'SECURITY_DEFINITIONS': {
      'Basic': {
            'type': 'basic'
      },
      'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
      }
   }
}

# JWT
#JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")
#JWT_SIGNING_KEY = os.getenv("JWT_SIGNING_KEY", None)
#JWT_VERIFYING_KEY = os.getenv("JWT_VERIFYING_KEY", None)

#SIMPLE_JWT = {
#    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("ACCESS_TOKEN_LIFETIME", 3))),
#    "REFRESH_TOKEN_LIFETIME": timedelta(minutes=int(os.getenv("REFRESH_TOKEN_LIFETIME", 15))),
#    "ROTATE_REFRESH_TOKENS": True,
#}

#if 'rs' in JWT_ALGORITHM.lower() and JWT_SIGNING_KEY and JWT_VERIFYING_KEY:
#    SIMPLE_JWT["ALGORITHM"] = JWT_ALGORITHM
#    SIMPLE_JWT["SIGNING_KEY"] = JWT_SIGNING_KEY
#    SIMPLE_JWT["VERIFYING_KEY"] = JWT_VERIFYING_KEY
#elif 'hs' in JWT_ALGORITHM.lower():
#    SIMPLE_JWT["ALGORITHM"] = JWT_ALGORITHM

